import sys
import os
sys.path.append(os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from db.mongodb import get_oi_collection
from datetime import datetime
import logging

logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

def cleanup_oi_data(symbol=None, target_date=None):
    """
    Cleans up potentially incorrect PCR/OI data.
    Targets data for 'today' by default.
    """
    coll = get_oi_collection()
    if target_date is None:
        target_date = datetime.now().strftime("%Y-%m-%d")

    query = {"date": target_date}
    if symbol:
        query["symbol"] = symbol

    # We specifically target data from 'live_engine' or points with anomalous PCR (> 3)
    # as these were likely generated by the bugged logic.
    bad_data_query = {
        "$and": [
            query,
            {"$or": [
                {"source": "live_engine"},
                {"pcr": {"$gt": 3.0}}
            ]}
        ]
    }

    # In MongoDB, if we sum OI incorrectly across all expiries, we get values like 6+.
    # Standard PCR is usually < 2.

    logger.info(f"Cleaning up OI data for {target_date}...")
    try:
        # Before deleting, let's see how many we are removing
        # (Need to handle mongomock/pymongo query syntax carefully with escape chars in bash)
        pass
    except:
        pass

    # Use a simpler query for the actual script to avoid bash escaping issues if run via shell
    # but here we are writing to a file, so it's fine.

    result = coll.delete_many({
        "date": target_date,
        "$or": [
            {"source": "live_engine"},
            {"pcr": {"$gt": 3.0}}
        ]
    })

    logger.info(f"Removed {result.deleted_count} potentially incorrect OI data points.")

if __name__ == "__main__":
    cleanup_oi_data()
